core/core/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("website.urls")),
]

urlpatterns += static(settings.STATIC_URL , document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

core/website/urls.py
from django.urls import path
from website.views import api_index

app_name = "website"

urlpatterns = [
    # path("", index_view, name="index"),
    path("", api_index, name= "index")
]

core/website/models.py
from django.db import models

# Create your models here.

core/website/views.py
from django.shortcuts import render
# Index view
def api_index(request):
    return render(request, "website/index.html")

core/templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.rtl.min.css' %}" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />
    <!-- my css -->
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <title>درود جهان</title>
  </head>
  <body>
    <!-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->
    <!-- navbar -->
    <nav class="navbar navbar-expand-md bg- my-nav my-nav-shadow">
      <div class="container">
        <a class="navbar-brand" href="#"><img src="" alt="" /></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active my-btn-hover text-white" aria-current="page" href="{% url 'website:index' %}">صفحه اصلی</a>
            </li>
            <li class="nav-item">
              <a class="nav-link my-btn-hover text-white" href="#">درباره ما</a>
            </li>
            <li class="nav-item">
              <a class="nav-link my-btn-hover text-white" href="#">تماس با ما</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">محصولات</a>
              <ul class="dropdown-menu bg-secondary">
                <li>
                  <a class="dropdown-item" href="#">دوره های اموزشی</a>
                </li>
                <li>
                  <a class="dropdown-item" href="#">کتاب ها</a>
                </li>
                <li>
                  <hr class="dropdown-divider" />
                </li>
                <li>
                  <a class="dropdown-item" href="#">سبد خرید</a>
                </li>
              </ul>
            </li>
            <li class="nav-item"></li>
          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2 my-bg-search" type="search" placeholder="به دنبال چه میگردی؟" aria-label="Search" />
            <button class="btn btn-outline-info text" type="submit">جستجو</button>
          </form>
        </div>
      </div>
    </nav>
    <!-- end navbar -->
    <!-- Header ends -->

    <!-- Content starts -->
    {% block content %}

    {% endblock %}
    <!-- Content Ends -->
<!-- footer -->
<footer class="mt-5 text-white">
  <div class="container">
    <div class="row align-items-center text-center">
      <div class="col line"></div>
    </div>
  </div>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-2 col-sm-6 mb-4"><img src="../abzar/images/1969px-Laravel.svg.png" alt="" class="w-75"></div>
      <div class="col-md-2 col-sm-6 mb-4"><img src="../abzar/images/Angular_full_color_logo.svg.png" alt="" class="w-75"></div>
      <div class="col-md-2 col-sm-6 mb-4"><img src="../abzar/images/Bootstrap_logo.svg" alt="" class="w-75"></div>
      <div class="col-md-2 col-sm-6 mb-4"><img src="../abzar/images/Octicons-mark-github.svg" alt="" class="w-75"></div>
      <div class="col-md-2 col-sm-6 mb-4"><img src="../abzar/images/React-icon.svg.png" alt="" class="w-75"></div>
      <div class="col-md-2 col-sm-6 mb-4"><img src="../abzar/images/Python-logo-notext.svg.png" alt="" class="w-75"></div>
    </div>
  
    <div class="row">
      <div class="col-4">
        <h5 class="mb-3">TwinFreaks</h5>
        <p class="text-white mb-3">اولین تیم تخصصی در زمینه طراحی وبسایت‌های متنوع و طراحی‌های خوش‌ساخت و جذاب</p>
        <p class="text-white mb-3">لینک‌های فضای مجازی:</p>
          <div class="row gX">
            <div class="col-2">      <i class="bi bi-instagram fs-1"></i></div>
            <div class="col-2">
              <i class="bi bi-telegram fs-1"></i>
            </div>
            <div class="col-2">
              <i class="bi bi-facebook fs-1 "></i>
            </div>
            <div class="col-2">
              <i class="bi bi-linkedin fs-1 "></i>
            </div>
          </div>
      </div>
      <div class="col-8">
        <!-- ul 1 -->
        <div class="row">
          <div class="col-4 ">
            <ul class="list-unstyled  ">
              <h6 class="my-ul-h">بخش های وبسایت</h6>
                <li ><a href="#" class="text-white"> صفحه اصلی</a></li>
                <li><a href="#" class="text-white"> محصولات </a></li>
                <li><a href="#" class="text-white"> گالری </a></li>
                <li><a href="#"class="text-white"> پشتیبانی </a></li>
            </ul>
          </div>
          <!-- ul 2 -->
        <div class="col-4">
          <ul class="list-unstyled ">
            <h6 class="my-ul-h">بخش های وبسایت</h6>
              <li ><a href="#" class="text-white"> صفحه اصلی</a></li>
              <li><a href="#" class="text-white"> محصولات </a></li>
              <li><a href="#" class="text-white"> گالری </a></li>
              <li><a href="#"class="text-white"> پشتیبانی </a></li>
          </ul>
          </div>
      <!-- ul 3 -->
      <div class="col-4">
        <ul class="list-unstyled ">
          <h6 class="my-ul-h">بخش های وبسایت</h6>
            <li ><a href="#" class="text-white"> صفحه اصلی</a></li>
            <li><a href="#" class="text-white"> محصولات </a></li>
            <li><a href="#" class="text-white"> گالری </a></li>
            <li><a href="#"class="text-white"> پشتیبانی </a></li>
        </ul>
        </div>
    </div>
  </div>
</footer>
      <!-- end section 5 -->
      <br />
  <!-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->
      <!-- bootstrap javaScript -->
      <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    </body>
  </html>

core/templates/website/index.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
  <!-- section 1 -->
  <div class="container mt-lg-5 mt-md-5 mt-sm-5">
    <div class="row my-row align-items-center">
      <div class="col-md col-lg mt-lg-1b fs-">
        <h4 class="mb-4 mt-lg-0 fw-bold text-white">لورم ایپسوم متن ساختگی</h4>
        <h5 class="text-primary mb-3 mb-lg-4 mt-lg-4">MyWebsite.ir</h5>
        <p class="lh-lg mb-lg-5 text-white">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است</p>

        <button type="button" class="btn btn-outline-info me-4">اطلاعات بیشتر</button>
        <button type="button" class="btn btn-outline-secondary">تماس با ما</button>
      </div>

      <div class="col-md col-lg-4 d-flex align-items-center mt-sm-5">
        <img src="{% static 'pictures/ui-design-26.png' %}" alt="" class="img-fluid my-mb" />
      </div>
    </div>
  </div>
  <div class="mb-4"></div>
  <!-- end section 1 -->

  <div class="container">
    <div class="row align-items-center text-center">
      <div class="col line"></div>
      <div class="col-2 mx-auto">
        <h3 class="text-white">خدمات ما</h3>
      </div>
      <div class="col line"></div>
    </div>
  </div>
  <div class="mb-4"></div>

  <!-- section 2 -->

  <!-- card 1 -->
  <section class="text-white">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-md-4">
          <i class="bi bi-stack fs-1 my-bi mb-4"></i>
          <h5 class="mb-3">خدمات ما</h5>
          <p class="mb-3">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است</p>
          <button type="button" class="btn btn-outline-info me-4">ثبت سفارش</button>
          <div class="mb-5"></div>
        </div>
        <div class="col-md-8">
          <div class="row">
            <div class="col-md-6">
              <div class="card text-center mb-4 my-card my-card-bg1 text-info">
                <div class="card-body">
                  <i class="bi bi-graph-up my-bi fs-1 mb-4 .my-card-i"></i>
                  <h5 class="card-title mb-3">لورم ایپسوم</h5>
                  <h6 class="lh-base card-text text-muted my-text-card">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است</h6>
                </div>
              </div>

              <div class="card text-center my-card my-card-bg2 text-info">
                <div class="card-body">
                  <i class="bi bi-graph-up my-bi fs-1 mb-4 .my-card-i"></i>
                  <h5 class="card-title mb-3">لورم ایپسوم</h5>
                  <h6 class="lh-base card-text text-muted my-text-card">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است</h6>
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <div class="card text-center mb-4 mt-5 my-card my-card-bg3 text-info">
                <div class="card-body">
                  <i class="bi bi-back my-bi fs-1 mb-4 .my-card-i"></i>
                  <h5 class="card-title mb-3">لورم ایپسوم</h5>
                  <h6 class="lh-base card-text text-muted my-text-card">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است</h6>
                </div>
              </div>

              <div class="card text-center my-card my-card-bg4 text-info">
                <div class="card-body">
                  <i class="bi bi-back my-bi fs-1 mb-4 .my-card-i"></i>
                  <h5 class="card-title mb-3">لورم ایپسوم</h5>
                  <h6 class="lh-base card-text text-muted my-text-card">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است</h6>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end section 2 -->

  <div class="mb-5"></div>
  <div class="container">
    <div class="row align-items-center text-center">
      <div class="col line"></div>
      <div class="col-md-3 col-lg-2 mx-auto">
        <h3 class="text-white">اشتراک ها</h3>
      </div>
      <div class="col line"></div>
    </div>
  </div>
  <div class="mb-4"></div>

  <!-- section 3 -->
  <section>
    <div class="text-center">
      <h4 class="fw-bold text-white mb-3">لورم ایپسوم متن</h4>
      <p class="fw-bold text-white mb-5">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است</p>
    </div>

    <div class="container">
      <div class="row align-items-center justify-content-center">
        <div class="col-md-4 col-lg-3">
          <div class="card text-center mb-4 my-card py-3 bg-secondary">
            <div class="card-body">
              <i class="bi bi-graph-up my-bi fs-1 mb-4"></i>
              <h5 class="card-title mb-3">مقدماتی</h5>
              <h5 class="card-title mb-3">10000تومان</h5>
              <p class="card-text text-muted fw-bold my-text-card">کاربر در ماه</p>
              <p class="card-text text-muted fw-bold my-text-card">فضا 30 GB</p>
              <p class="card-text text-muted fw-bold my-text-card">دسترسی کامل</p>
              <button class="btn btn-outline-info mt-4">خرید</button>
            </div>
          </div>
        </div>
        <div class="col-md-4 col-lg-3">
          <div class="card text-center mb-4 my-card my-bg-1 py-5 bg-dark">
            <div class="card-body">
              <i class="bi bi-graph-up my-bi fs-1 mb-4"></i>
              <h5 class="card-title mb-3 text-light">مقدماتی</h5>
              <h5 class="card-title mb-3 text-light">10000تومان</h5>
              <p class="card-text text-light fw-bold">کاربر در ماه</p>
              <p class="card-text text-light fw-bold">فضا 30 GB</p>
              <p class="card-text text-light fw-bold">دسترسی کامل</p>
              <button class="btn btn-outline-light mt-4">خرید</button>
            </div>
          </div>
        </div>
        <div class="col-md-4 col-lg-3">
          <div class="card text-center mb-4 my-card py-3 bg-secondary">
            <div class="card-body">
              <i class="bi bi-graph-up my-bi fs-1 mb-4"></i>
              <h5 class="card-title mb-3 my-text-card">مقدماتی</h5>
              <h5 class="card-title mb-3 my-text-card">10000تومان</h5>
              <p class="card-text text-muted fw-bold my-text-card">کاربر در ماه</p>
              <p class="card-text text-muted fw-bold my-text-card">فضا 30 GB</p>
              <p class="card-text text-muted fw-bold my-text-card">دسترسی کامل</p>
              <button class="btn btn-outline-info mt-4">خرید</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- end section 3 -->

  <div class="mb-5"></div>
  <div class="container">
    <div class="row align-items-center text-center">
      <div class="col line"></div>
      <div class="col-md-3 col-lg-2 mx-auto">
        <h3 class="text-white">گالری تصاویر</h3>
      </div>
      <div class="col line"></div>
    </div>
  </div>
  <div class="mb-4"></div>

  <!-- section 4 -->
  <section class="my-section text-light">
    <div class="container">
      <div class="row text-center">
        <h4 class="fw-bold mb-3">لورم ایپسوم متن</h4>
        <p class="fw-bold mb-5">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است</p>
      </div>
      <div class="row">
        <div id="carouselExampleIndicators" class="carousel slide rounded">
          <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
          </div>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img src="{% static 'pictures/Nature HD Wallpapers 188.jpg' %}" class="d-block w-100 rounded-4" alt="..." />
            </div>
            <div class="carousel-item">
              <img src="{% static 'pictures/Nature HD Wallpapers 217.jpg' %}" class="d-block w-100 rounded-4" alt="..." />
            </div>
            <div class="carousel-item">
              <img src="{% static 'pictures/Nature HD Wallpapers 243.jpg' %}" class="d-block w-100 rounded-4" alt="..." />
            </div>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
      </div>

      <button class="btn btn-outline-light mt-5 py-3 px-4">مشاهده گالری</button>
    </div>
    <br /><br /><br />
  </section>
  <!-- end section 4 -->

  <div class="mb-5"></div>
  <div class="container">
    <div class="row align-items-center text-center">
      <div class="col line"></div>
      <div class="col-md-3 col-lg-2 mx-auto">
        <h3 class="text-white">تماس با ما</h3>
      </div>
      <div class="col line"></div>
    </div>
  </div>
  <div class="mb-4"></div>

  <!-- section 5 -->
  <section>
    <div class="container">
      <div class="row text-center">
        <h4 class="fw-bold text-white mb-3">لورم ایپسوم متن</h4>
        <p class="fw-bold mb-5 text-white">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است</p>
      </div>
      <div class="row align-items-center">
        <div class="col-md-6">
          <form action="" method="post">
            <div class="mb-3">
              <label for="exampleFormControlInput1" class="form-label text-white">ایمیل</label>
              <input type="email" class="form-control bg-light" id="exampleFormControlInput1" placeholder="name@example.com" />
            </div>
            <div class="mb-3">
              <label for="exampleFormControlTextarea1" class="form-label text-white">متن پیام</label>
              <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
            </div>
            <button class="btn btn-outline-info" type="submit">ارسال پیام</button>
          </form>
        </div>
        <div class="col-md-6 col-lg-5 offset-lg-1">
          <img src="{% static 'pictures/coding-29.png' %}" alt="" class="img-fluid" />
        </div>
      </div>
    </div>
  </section>
  <!-- end section 5 -->
{% endblock %}